# Generated by Django 2.2.24 on 2022-03-28 19:57

from django.db import migrations

def mark_new_buildings(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = True if flat.construction_year >= 2015 else False
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20220327_1845'),
    ]

    operations = [
        migrations.RunPython(mark_new_buildings)
    ]
