# Generated by Django 2.2.24 on 2022-04-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220403_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='own_flats',
            field=models.ManyToManyField(db_index=True, related_name='owned_by', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
