# Generated by Django 2.2.24 on 2022-04-04 21:43

from django.db import migrations


def set_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        flats = Flat.objects.filter(owner=owner.owner).all()
        owner.flats.add()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220403_1801'),
    ]

    operations = [
    ]
