# Generated by Django 2.2.24 on 2022-04-04 21:43

from django.db import migrations


def set_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner = Owner.objects.get(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )
        owner.own_flats.add(flat)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20220403_1801'),
    ]

    operations = [
        migrations.RunPython(set_owners)
    ]
